import { useState } from 'react';
import { Link, Navigate, useNavigate } from 'react-router-dom';
import { api } from '../services/api';
import { useAuth } from '../auth/AuthContext';
const message=(error:unknown)=>error instanceof Error?error.message:'No fue posible completar la operación.';
export function RegisterPage(){const nav=useNavigate();const [error,setError]=useState('');const [data,setData]=useState({firstName:'',lastName:'',email:'',phone:'',password:'',confirmPassword:''});const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');if(data.password!==data.confirmPassword){setError('Las contraseñas no coinciden.');return;}try{await api.register(data);nav(`/verificar-correo?email=${encodeURIComponent(data.email)}`);}catch(e){setError(message(e));}};return <AuthForm title="Crea tu cuenta"><form onSubmit={submit}>{[['firstName','Nombre'],['lastName','Apellidos'],['email','Correo electrónico'],['phone','Teléfono'],['password','Contraseña (12 caracteres mínimo)'],['confirmPassword','Confirmar contraseña']].map(([key,label])=><label key={key}>{label}<input required type={key.includes('password')?'password':key==='email'?'email':'text'} value={data[key as keyof typeof data]} onChange={e=>setData({...data,[key]:e.target.value})}/></label>)}{error&&<p role="alert">{error}</p>}<button>Registrarme</button></form><p>¿Ya tienes cuenta? <Link to="/iniciar-sesion">Inicia sesión</Link></p></AuthForm>}
export function VerifyPage(){const params=new URLSearchParams(location.search);const [email,setEmail]=useState(params.get('email')??'');const [code,setCode]=useState('');const [notice,setNotice]=useState('');const [seconds,setSeconds]=useState(0);const nav=useNavigate();const verify=async(e:React.FormEvent)=>{e.preventDefault();try{await api.verify({email,code});nav('/iniciar-sesion');}catch(e){setNotice(message(e));}};const resend=async()=>{try{await api.resend(email);setNotice('Si la cuenta requiere verificación, se envió un código.');setSeconds(60);const id=window.setInterval(()=>setSeconds(s=>{if(s<=1){clearInterval(id);return 0;}return s-1;}),1000);}catch(e){setNotice(message(e));}};return <AuthForm title="Verifica tu correo"><form onSubmit={verify}><label>Correo electrónico<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Código de 6 dígitos<input required inputMode="numeric" pattern="[0-9]{6}" value={code} onChange={e=>setCode(e.target.value)}/></label>{notice&&<p role="alert">{notice}</p>}<button>Verificar cuenta</button></form><button type="button" disabled={seconds>0} onClick={()=>void resend()}>{seconds?`Reenviar en ${seconds}s`:'Reenviar código'}</button></AuthForm>}
export function LoginPage(){const {user,refresh}=useAuth();const nav=useNavigate();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState('');if(user)return <Navigate to="/mi-cuenta" replace/>;const submit=async(e:React.FormEvent)=>{e.preventDefault();try{await api.login({email,password});await refresh();nav('/mi-cuenta');}catch(e){setError(message(e));}};return <AuthForm title="Inicia sesión"><form onSubmit={submit}><label>Correo electrónico<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Contraseña<input required type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert">{error}</p>}<button>Entrar</button></form><Link to="/registro">Crear cuenta</Link></AuthForm>}
export function AccountPage(){const {user,loading,logout}=useAuth();const nav=useNavigate();if(loading)return <p>Cargando sesión…</p>;if(!user)return <Navigate to="/iniciar-sesion" replace/>;return <AuthForm title="Mi cuenta"><p>{user.firstName} {user.lastName}</p><p>{user.email}</p><p>Rol: {user.role}</p><button onClick={()=>void logout().then(()=>nav('/iniciar-sesion'))}>Cerrar sesión</button></AuthForm>}
function AuthForm({title,children}:{title:string;children:React.ReactNode}){return <main className="auth-page"><h1>{title}</h1>{children}</main>}
